train: ../train/images
val: ../valid/images
test: ../test/images

nc: 1
names: ['car']

roboflow:
  workspace: projet-k8xlm
  project: traficurbain_vehicules
  version: 1
  license: CC BY 4.0
  url: https://universe.roboflow.com/projet-k8xlm/traficurbain_vehicules/dataset/1